#!/usr/bin/bash
# Repository:   https://github.com/Python-utilities
# File Name:    tools/cpp_project/bash_aliases_for_docker
# Description:  bash aliases for interactive use of docker containers
#
# Copyright (C) 2024 Dieter J Kybelksties <github@kybelksties.com>
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
#
# @date: 2024-07-13
# @author: Dieter J Kybelksties


[[ "${0}" != "${BASH_SOURCE[0]}" ]] && THIS_FILE="${BASH_SOURCE[0]}" || THIS_FILE="${0}"
THIS_DIR=$(realpath "$(dirname ${THIS_FILE})")

CURRENT_OS=$(uname)

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# User specific aliases and functions

CURRENT_OS=$(uname)
echo "OS is '${CURRENT_OS}'"

IS_LINUX=No
if [[ ${CURRENT_OS} =~ "Linux" ]]; then
	IS_LINUX=Yes
fi

alias l="ls -Fax"
alias ll="ls -Fasl"
alias v=vim
alias m=less
alias cls=clear
alias findExe="find . -perm -u+x -type f "
alias h=history
alias myps="ps -eaf | ${GREP} $(id | cut -f2 -d'(' | cut -f1 -d')')"
alias cd..="cd .."
alias cd-="cd -"
alias hexdump="od -x -A x"
alias mystat="prstat -s rss -u $(whoami)"
export GREP_COLORS="ms=01;31:mc=01;31:sl=:cx=:fn=36:ln=32:bn=32:se=36"
export GREP_OPTIONS=--color

# ANSI color codes
RS="\[\033[0m\]"    # reset
HC="\[\033[1m\]"    # hicolor
UL="\[\033[4m\]"    # underline
INV="\[\033[7m\]"   # inverse background and foreground
FBLK="\[\033[30m\]" # foreground black
FRED="\[\033[31m\]" # foreground red
FGRN="\[\033[32m\]" # foreground green
FYEL="\[\033[33m\]" # foreground yellow
FBLE="\[\033[34m\]" # foreground blue
FMAG="\[\033[35m\]" # foreground magenta
FCYN="\[\033[36m\]" # foreground cyan
FWHT="\[\033[37m\]" # foreground white
BBLK="\[\033[40m\]" # background blackG
BRED="\[\033[41m\]" # background red
BGRN="\[\033[42m\]" # background green
BYEL="\[\033[43m\]" # background yellow
BBLE="\[\033[44m\]" # background blue
BMAG="\[\033[45m\]" # background magenta
BCYN="\[\033[46m\]" # background cyan
BWHT="\[\033[47m\]" # background white

ERS='\033[0m'    # reset
EHC='033[1m'     # hicolor
EUL='\033[4m'    # underline
EINV='\033[7m'   # inverse background and foreground
EFBLK='\033[30m' # foreground black
EFRED='\033[31m' # foreground red
EFGRN='\033[32m' # foreground green
EFYEL='\033[33m' # foreground yellow
EFBLE='\033[34m' # foreground blue
EFMAG='\033[35m' # foreground magenta
EFCYN='\033[36m' # foreground cyan
EFWHT='\033[37m' # foreground white
EBBLK='\033[40m' # background blackG
EBRED='\033[41m' # background red
EBGRN='\033[42m' # background green
EBYEL='\033[43m' # background yellow
EBBLE='\033[44m' # background blue
EBMAG='\033[45m' # background magenta
EBCYN='\033[46m' # background cyan
EBWHT='\033[47m' # background white

export MY_HOST=$(hostname)

function prompt() {
	PS1="\u@\h [\t]> "

  DOCKPROMPT="python_runner"
	if [ "${IS_LINUX}X" = "YesX" ]; then
		PS1="\$(date +%H:%M:%S) ${FYEL}\u@${DOCKPROMPT} ${FRED}[${FCYN}\w ${FRED}]>${RS} "
		PS2='continue-> '
		PS4='$0.$LINENO+ '
	fi
}

prompt

. /.venv/bin/activate
