#!/usr/bin/bash
[[LICENCE]]

[[ "${0}" != "${BASH_SOURCE[0]}" ]] && THIS_FILE="${BASH_SOURCE[0]}" || THIS_FILE="${0}"
THIS_DIR=$(realpath "$(dirname ${THIS_FILE})")

[ -f "${THIS_DIR}/build/bin/[[PROJECT_NAME_TEMPLATE_LOWER]]" ] || {
    mkdir -p "${THIS_DIR}/build"
    pushd "${THIS_DIR}/build"
    cmake ..
    make -j $(nproc --all)
    popd
}

docker-compose build

