#!/usr/bin/bash

{{cookiecutter.licence}}

[[ "${0}" != "${BASH_SOURCE[0]}" ]] && THIS_FILE="${BASH_SOURCE[0]}" || THIS_FILE="${0}"
THIS_DIR=$(realpath "$(dirname ${THIS_FILE})")

[ -f "${THIS_DIR}/build/bin/{{cookiecutter.project_name_lower}}" ] || {
    mkdir -p "${THIS_DIR}/build"
    pushd "${THIS_DIR}/build"
    cmake -Wno-dev .. || {
      echo "Error configuring project"
      exit 1
    }

    cmake --build . || {
      echo "Error building project"
      exit 1
    }

    popd
}

{{cookiecutter.docker_build_command}}

