[[LICENCE]]
version: '3'
services:
  [[SERVICE_NAME_WITH_MESSAGING_TYPE]]_server:
    image: [[SERVICE_NAME_WITH_MESSAGING_TYPE]]_server:${VERSION}
    build:
      context: .
      dockerfile: Dockerfile.[[SERVICE_NAME_LOWER]]_server
    ports:
      - ${PORT}:${PORT}
    command: -c "./[[SERVICE_NAME_LOWER]]_[[MESSAGING_TYPE]]_server --port ${PORT}"
  [[SERVICE_NAME_LOWER]]_[[MESSAGING_TYPE]]client:
    image: [[SERVICE_NAME_WITH_MESSAGING_TYPE]]_client:${VERSION}
    build:
      context: .
      dockerfile: Dockerfile.[[SERVICE_NAME_LOWER]]_client
    command: -c "./[[SERVICE_NAME_WITH_MESSAGING_TYPE]]_client --server [[SERVICE_NAME_WITH_MESSAGING_TYPE]]_server --port ${PORT}"
    depends_on:
      - [[SERVICE_NAME_WITH_MESSAGING_TYPE]]_server
      
