{{cookiecutter.licence}}
version: '3'
services:
  {{cookiecutter.service_name_with_messaging_type}}_server:
    image: {{cookiecutter.service_name_with_messaging_type}}_server:${VERSION}
    build:
      context: .
      dockerfile: Dockerfile.{{cookiecutter.service_name_lower}}_server
    ports:
      - ${PORT}:${PORT}
    command: -c "./{{cookiecutter.service_name_lower}}_{{cookiecutter.messaging_type}}_server --port ${PORT}"
  {{cookiecutter.service_name_lower}}_{{cookiecutter.messaging_type}}client:
    image: {{cookiecutter.service_name_with_messaging_type}}_client:${VERSION}
    build:
      context: .
      dockerfile: Dockerfile.{{cookiecutter.service_name_lower}}_client
    command: -c "./{{cookiecutter.service_name_with_messaging_type}}_client --server {{cookiecutter.service_name_with_messaging_type}}_server --port ${PORT}"
    depends_on:
      - {{cookiecutter.service_name_with_messaging_type}}_server
      
