{{cookiecutter.licence}}

version: '3'
services:
  {{cookiecutter.project_name_lower}}:
    image: {{cookiecutter.project_name_lower}}:${VERSION}
    build:
      context: .
      dockerfile: Dockerfile
    command: -c ./{{cookiecutter.project_name_lower}}
